/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dokotest;

/**
 *
 * @author Acer
 */
public class branchlocationmgmt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(branchlocationmgmt.class.getName());

    /**
     * Creates new form Employee_Dashboard
     */
    public branchlocationmgmt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        dashboard = new javax.swing.JButton();
        MyShipments = new javax.swing.JButton();
        ManageOrders = new javax.swing.JButton();
        OrdersHistory = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        MyProfile = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Topbar = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Dashboard");
        setBackground(new java.awt.Color(238, 233, 223));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(238, 233, 223));
        MainPanel.setPreferredSize(new java.awt.Dimension(1050, 600));
        MainPanel.setLayout(null);

        Sidebar.setBackground(new java.awt.Color(33, 38, 49));
        Sidebar.setLayout(null);

        dashboard.setBackground(new java.awt.Color(33, 38, 49));
        dashboard.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        Sidebar.add(dashboard);
        dashboard.setBounds(6, 86, 168, 50);

        MyShipments.setBackground(new java.awt.Color(33, 38, 49));
        MyShipments.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyShipments.setForeground(new java.awt.Color(255, 255, 255));
        MyShipments.setText("Manage Users");
        Sidebar.add(MyShipments);
        MyShipments.setBounds(6, 153, 168, 50);

        ManageOrders.setBackground(new java.awt.Color(216, 140, 81));
        ManageOrders.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageOrders.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrders.setText("Workload");
        Sidebar.add(ManageOrders);
        ManageOrders.setBounds(6, 214, 168, 50);

        OrdersHistory.setBackground(new java.awt.Color(33, 38, 49));
        OrdersHistory.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        OrdersHistory.setForeground(new java.awt.Color(255, 255, 255));
        OrdersHistory.setText("Branch and Networks");
        Sidebar.add(OrdersHistory);
        OrdersHistory.setBounds(6, 281, 168, 50);

        logout.setBackground(new java.awt.Color(33, 38, 49));
        logout.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 51));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.setText("Logout");
        Sidebar.add(logout);
        logout.setBounds(6, 541, 168, 53);
        Sidebar.add(jSeparator1);
        jSeparator1.setBounds(0, 532, 180, 3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        Sidebar.add(jLabel1);
        jLabel1.setBounds(180, 541, 0, 53);
        Sidebar.add(jSeparator2);
        jSeparator2.setBounds(0, 69, 180, 10);

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\DOKOImage.jpeg")); // NOI18N
        jLabel13.setText("jLabel13");
        Sidebar.add(jLabel13);
        jLabel13.setBounds(0, 0, 180, 70);

        MyProfile.setBackground(new java.awt.Color(33, 38, 49));
        MyProfile.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfile.setForeground(new java.awt.Color(255, 255, 255));
        MyProfile.setText("Manage Orders");
        MyProfile.addActionListener(this::MyProfileActionPerformed);
        Sidebar.add(MyProfile);
        MyProfile.setBounds(10, 340, 160, 45);

        jButton4.setBackground(new java.awt.Color(33, 38, 49));
        jButton4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Price Configuration");
        Sidebar.add(jButton4);
        jButton4.setBounds(6, 394, 168, 45);

        jButton5.setBackground(new java.awt.Color(33, 38, 49));
        jButton5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("My Profile");
        Sidebar.add(jButton5);
        jButton5.setBounds(6, 451, 168, 45);

        MainPanel.add(Sidebar);
        Sidebar.setBounds(0, 0, 180, 600);

        Topbar.setLayout(null);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        Topbar.add(profile);
        profile.setBounds(757, 0, 0, 82);

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        Topbar.add(Profile);
        Profile.setBounds(670, 0, 0, 0);

        jLabel9.setText("Username");
        Topbar.add(jLabel9);
        jLabel9.setBounds(760, 10, 90, 30);

        jLabel10.setText("Role");
        Topbar.add(jLabel10);
        jLabel10.setBounds(760, 50, 43, 16);

        MainPanel.add(Topbar);
        Topbar.setBounds(186, 0, 0, 0);

        jPanel1.setLayout(null);

        jLabel2.setText("Branch ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(68, 66, 79, 16);

        jLabel3.setText("Branch Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(68, 125, 90, 16);

        jLabel4.setText("Branch Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(68, 180, 90, 16);

        jLabel5.setText("Branch Phone Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(68, 235, 120, 16);

        jLabel6.setText("Receiver's Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(68, 286, 100, 16);

        jTextField1.setText("#2345");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 60, 147, 31);

        jTextField2.setText("Dillibazar");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 120, 147, 31);

        jTextField3.setText("dillibazar22@gmail.com");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 180, 147, 30);

        jTextField4.setText("9800000000");
        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 230, 146, 30);

        jTextField5.setText("Kapan");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(210, 280, 146, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Branch Details");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 120, 33);

        jButton1.setBackground(new java.awt.Color(168, 168, 168));
        jButton1.setText("Edit");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 8, 99, 35);

        jButton3.setBackground(new java.awt.Color(168, 168, 168));
        jButton3.setText("Save");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);
        jButton3.setBounds(620, 330, 99, 35);

        MainPanel.add(jPanel1);
        jPanel1.setBounds(200, 220, 740, 370);

        jTextField7.setText("# Enter Branch ID");
        jTextField7.addActionListener(this::jTextField7ActionPerformed);
        MainPanel.add(jTextField7);
        jTextField7.setBounds(200, 90, 430, 50);

        jPanel2.setLayout(null);
        MainPanel.add(jPanel2);
        jPanel2.setBounds(180, 0, 870, 70);

        jButton2.setBackground(new java.awt.Color(168, 168, 168));
        jButton2.setText("Create+");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        MainPanel.add(jButton2);
        jButton2.setBounds(669, 88, 96, 48);

        jLabel7.setText("Total Orders");
        MainPanel.add(jLabel7);
        jLabel7.setBounds(250, 150, 100, 16);

        jLabel11.setText("Total Employees");
        MainPanel.add(jLabel11);
        jLabel11.setBounds(360, 150, 100, 16);

        jPanel3.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("100");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(0, 0, 90, 40);

        MainPanel.add(jPanel3);
        jPanel3.setBounds(360, 170, 90, 40);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel4);
        jPanel4.setBounds(250, 170, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void MyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new branchlocationmgmt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ManageOrders;
    private javax.swing.JButton MyProfile;
    private javax.swing.JButton MyShipments;
    private javax.swing.JButton OrdersHistory;
    private javax.swing.JLabel Profile;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel Topbar;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton logout;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
